[profile.default]
version = "0.8.10"
src = "src"
out = "out"
libs = ["lib"]
evm_version="shanghai"
build_info = true
extra_output = ["storageLayout"]
ffi = true
ast = true

[rpc_endpoints]
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC}"
bartio = "${BARTIO_RPC}"
imola = "${IMOLA_RPC}"

[invariant]
runs = 10
depth = 100
fail_on_revert = false

[fmt]
multiline_func_header="params_first"
line_length=100
ignore=[
    "*/**/IOverlayV1Market.sol",
    "*/**/IOverlayV1State.sol"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
